In [2]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
%matplotlib inline 

from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import MinMaxScaler 
from sklearn.model_selection import train_test_split 

from sklearn.linear_model import LinearRegression

In [3]:
diamonds=pd.read_csv('diamonds.csv')

In [4]:
diamonds

,Unnamed: 0,carat,cut,color,clarity,depth,table,price,x,y,z
0,1,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43
1,2,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31
2,3,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31
3,4,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63
4,5,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75
...,...,...,...,...,...,...,...,...,...,...,...
53935,53936,0.72,Ideal,D,SI1,60.8,57.0,2757,5.75,5.76,3.50
53936,53937,0.72,Good,D,SI1,63.1,55.0,2757,5.69,5.75,3.61
53937,53938,0.70,Very Good,D,SI1,62.8,60.0,2757,5.66,5.68,3.56
53938,53939,0.86,Premium,H,SI2,61.0,58.0,2757,6.15,6.12,3.74
53939,53940,0.75,Ideal,D,SI2,62.2,55.0,2757,5.83,5.87,3.64

In [5]:
diamonds.drop(['Unnamed: 0'],axis=1,inplace=True)

In [6]:
diamonds

       carat        cut color clarity  depth  table  price     x     y     z
0       0.23      Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1       0.21    Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2       0.23       Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3       0.29    Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4       0.31       Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75
...      ...        ...   ...     ...    ...    ...    ...   ...   ...   ...
53935   0.72      Ideal     D     SI1   60.8   57.0   2757  5.75  5.76  3.50
53936   0.72       Good     D     SI1   63.1   55.0   2757  5.69  5.75  3.61
53937   0.70  Very Good     D     SI1   62.8   60.0   2757  5.66  5.68  3.56
53938   0.86    Premium     H     SI2   61.0   58.0   2757  6.15  6.12  3.74
53939   0.75      Ideal     D     SI2   62.2   55.0   2757  5.83  5.87  3.64

[53940 rows x 10 columns]

In [7]:
y=diamonds['price']
x=diamonds.drop('price',axis=1)

In [8]:
x

       carat        cut color clarity  depth  table     x     y     z
0       0.23      Ideal     E     SI2   61.5   55.0  3.95  3.98  2.43
1       0.21    Premium     E     SI1   59.8   61.0  3.89  3.84  2.31
2       0.23       Good     E     VS1   56.9   65.0  4.05  4.07  2.31
3       0.29    Premium     I     VS2   62.4   58.0  4.20  4.23  2.63
4       0.31       Good     J     SI2   63.3   58.0  4.34  4.35  2.75
...      ...        ...   ...     ...    ...    ...   ...   ...   ...
53935   0.72      Ideal     D     SI1   60.8   57.0  5.75  5.76  3.50
53936   0.72       Good     D     SI1   63.1   55.0  5.69  5.75  3.61
53937   0.70  Very Good     D     SI1   62.8   60.0  5.66  5.68  3.56
53938   0.86    Premium     H     SI2   61.0   58.0  6.15  6.12  3.74
53939   0.75      Ideal     D     SI2   62.2   55.0  5.83  5.87  3.64

[53940 rows x 9 columns]

In [9]:
print(f"cuts: {len(x['cut'].unique())}")
print(f"colors: {len(x['color'].unique())}")
print(f"clarities: {len(x['clarity'].unique())}")

cuts: 5
colors: 7
clarities: 8

In [10]:
encoder=LabelEncoder()
x['cut']=encoder.fit_transform(x['cut'])
cut_categories={index: label for index, label in enumerate(encoder.classes_)}
cut_categories

{0: 'Fair', 1: 'Good', 2: 'Ideal', 3: 'Premium', 4: 'Very Good'}

In [11]:
x['color']=encoder.fit_transform(x['color'])
color_categories={index: label for index, label in enumerate(encoder.classes_)}
color_categories

{0: 'D', 1: 'E', 2: 'F', 3: 'G', 4: 'H', 5: 'I', 6: 'J'}

In [12]:
x['clarity']=encoder.fit_transform(x['clarity'])
clarity_categories={index: label for index, label in enumerate(encoder.classes_)}
clarity_categories

{0: 'I1',
 1: 'IF',
 2: 'SI1',
 3: 'SI2',
 4: 'VS1',
 5: 'VS2',
 6: 'VVS1',
 7: 'VVS2'}

In [13]:
x

       carat  cut  color  clarity  depth  table     x     y     z
0       0.23    2      1        3   61.5   55.0  3.95  3.98  2.43
1       0.21    3      1        2   59.8   61.0  3.89  3.84  2.31
2       0.23    1      1        4   56.9   65.0  4.05  4.07  2.31
3       0.29    3      5        5   62.4   58.0  4.20  4.23  2.63
4       0.31    1      6        3   63.3   58.0  4.34  4.35  2.75
...      ...  ...    ...      ...    ...    ...   ...   ...   ...
53935   0.72    2      0        2   60.8   57.0  5.75  5.76  3.50
53936   0.72    1      0        2   63.1   55.0  5.69  5.75  3.61
53937   0.70    4      0        2   62.8   60.0  5.66  5.68  3.56
53938   0.86    3      4        3   61.0   58.0  6.15  6.12  3.74
53939   0.75    2      0        3   62.2   55.0  5.83  5.87  3.64

[53940 rows x 9 columns]

In [14]:
scaler=MinMaxScaler()
x=scaler.fit_transform(x)

In [15]:
x_train,x_test,y_train,y_test= train_test_split(x,y,train_size=0.8)

In [16]:
LR=LinearRegression()
LR.fit(x_train,y_train)

LinearRegression()

In [17]:
print(f"{LR.score(x_test,y_test)}")

0.8851542228793271

In [18]:
from sklearn.metrics import mean_squared_error
y_predictions=LR.predict(x_test)
print("Mean squared error: {}".format(mean_squared_error(y_test,y_predictions)))

Mean squared error: 1833140.6908588824

In [19]:
from sklearn.model_selection import cross_val_score
def display_scores(scores):
    print("Scores:", scores)
    print("Mean:", scores.mean())
    print("Standard deviation:", scores.std())
lin_scores = cross_val_score(LR, x, y,
scoring="neg_mean_squared_error", cv=10)
lin_rmse_scores = np.sqrt(-lin_scores)
display_scores(lin_rmse_scores)

Scores: [1014.75417063 1147.06555037 1225.4403972  1690.07822248 3127.4923956
 1774.49063582  782.30384805  731.05478504  665.87909348  779.04895745]
Mean: 1293.7608056131041
Standard deviation: 713.5938693147442